version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        volumes:
            - postgresdb-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgresdb-data:
